
CREATE TABLE PESSOA (
	ID INT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    ID_CARGO INT 
);
    
CREATE TABLE CARGO (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR (50)
);

ALTER TABLE PESSOA ADD CONSTRAINT FOREIGN KEY (ID) REFERENCES CARGO (ID);
    
INSERT INTO CARGO (DESCRICAO) VALUES ('PRESIDENTE'),('DIRETOR'),('CHEFE');
INSERT INTO CARGO (DESCRICAO) VALUES ('PRESIDENTE'),('DIRETOR'),('CHEFE');
INSERT INTO PESSOA (NOME, ID_CARGO) VALUES ('ALAN', 1),('EURICO', 2),('ALISON', 3);
INSERT INTO PESSOA (NOME, ID_CARGO) VALUES ('LE GOMES', 1),('PE GOMES', 2),('AN GOMES', 3);

SELECT pessoa.NOME, cargo.DESCRICAO FROM PESSOA  INNER JOIN CARGO  ON PESSOA.ID_CARGO = CARGO.ID;

WHERE CARGO.DESCRICAO LIKE '%DIRETOR%';
	